### ISSUE TITLE
Content in editor isn't updated when the "Quote reply" button is clicked in GitHub

### ISSUE THREAD

**Issue by Andrew15-5** [fregante/GhostText#327] opened 2024-09-08 14:36 UTC
### Description and repro

When I want to quote some complex text in GitHub, I use the "Quote reply" button that inserts selected text or the whole message verbatim in the currently active field. But when it pastes the selected content in the editable field, it doesn't update the content shown in the connected editor.

As a workaround, I always have to type anything manually in the browser tab for the content to become in sync again. This is not ideal. Can the "on non-physical content change" event be caught and handled? AFAIK, in JS, some events are triggered when a user manually inputs something. But other inputs can be programmable and therefore must be handled separately, if possible.

### Browser(s) tried

Firefox 130.0

### Editor(s) tried

Neovim 0.10.0

**Comment by fregante** [comment] 2024-09-08 15:19
Duplicate of https://github.com/fregante/GhostText/issues/84

**Closed by fregante** 2024-09-08 15:19 UTC
Labels: bug

**Comment by Andrew15-5** [comment] 2024-09-08 18:59
Oh, no, 2016... XD

**Comment by Andrew15-5** [comment] 2024-09-08 19:05
And also when you upload a file. It will automatically create a link which isn't shown in the editor unless you manually do something. Same thing, but different.
