### ISSUE TITLE
Disconnected on save

### ISSUE THREAD

**Issue by Paklenizmaj** [fregante/GhostText#323] opened 2024-07-18 16:56 UTC
### Description and repro

When using GhostText on Chrome with VS Code, I experience a disconnection every time I press Ctrl+S. This is problematic because I habitually press Ctrl+S after making any change. Disconnecting on file save is not desirable and interrupts my workflow.

Steps to Reproduce:

Install GhostText on Chrome.
Connect GhostText to VS Code.
Make any change in the VS Code editor.
Press Ctrl+S to save the file.
Expected Behavior:
GhostText should remain connected after saving the file with Ctrl+S.

Actual Behavior:
GhostText disconnects every time Ctrl+S is pressed.

Environment:

Browser: Chrome
Editor: VS Code
GhostText Version: 24.7.6
Operating System: Windows 10

### Browser(s) tried

Chrome

### Editor(s) tried

VS Code

**Comment by fregante** [comment] 2024-07-18 17:12
Duplicate of https://github.com/fregante/GhostText/issues/292

**Closed by fregante** 2024-07-18 17:12 UTC
Labels: bug

**Comment by Paklenizmaj** [comment] 2024-07-19 08:09
My solution for this problem is a little ahk script, This script is active only if I use GhostText, so I do not need to change a any vscode or system settings.

```ahk
#IfWinActive ahk_class Chrome_WidgetWin_1 ahk_exe Code.exe
^s::
return
#IfWinActive
```
